apiVersion: v1
kind: Service
metadata:
  name: manejo-finanzas-mcp
spec:
  selector:
    app: manejo-finanzas-mcp
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: mcp
  type: LoadBalancer